elm:
  - "latest-0.19.1"

elm-format: "0.8.2"

env:
  matrix:
    - ELM_VERSION=0.19.0 TARGET_NODE_VERSION=node

install:
  - node --version
  - npm --version
  - npm install -g elm-test elm-format

script:
  - elm-format --validate src tests
  - npm test
